---
- name: Install Docker
  hosts: all
  become: yes

  vars:
    docker_apt_key: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: "{{ docker_apt_key }}"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

---

- name: Deploy Rancher
  hosts: all
  become: yes

  vars:
    rancher_version: "v2.7.2"
    rancher_server_port: 8080

  tasks:
    - name: Run Rancher container
      docker_container:
        name: rancher
        image: rancher/rancher:{{ rancher_version }}
        ports:
          - "{{ rancher_server_port }}:80"
          - "8443:443"
        state: started
        restart_policy: always
